### ISSUE TITLE
Add support for 1.2

### ISSUE THREAD

**Issue by MaikKlein** [MaikKlein/ash#263]
Version 1.2 got released today https://www.khronos.org/news/press/khronos-group-releases-vulkan-1.2

We should try to support it soonish. Might need to update the vk.xml parser again.

- [x] Update the parser / generator to output 1.2 ffi bindings
- [x] Expose a 1.2 high level wrapper
- [ ] Add a simple 1.2 example to test some of the new features.

**Comment by AlexanderEkdahl** [comment]
I'm going to make an attempt at this. Will reach out on gitter if I get stuck.

**Comment by MaikKlein** [comment]
> I'm going to make an attempt at this. Will reach out on gitter if I get stuck.

Thanks, I'll make sure to be more active on gitter :), don't hesitate to ask questions. Also the generator is not the cleanest code. If you want to refactor something to make it easier, just do it.

**Comment by AlexanderEkdahl** [comment]
What should be done about changes in the Vulkan API that ends up being a breaking semver change in the Rust API?

For example `PhysicalDeviceDriverPropertiesKHR` -> `PhysicalDeviceDriverProperties` as the latter has been promoted from an extension. 

Unless I am mistaken not having `PhysicalDeviceDriverPropertiesKHR` would make it near impossible to use `ash` for pre-1.2 work unless you use an older version of `ash`?

**Comment by MaikKlein** [comment]
I think those should just become type aliases. Similar to https://docs.rs/ash/0.29.0/ash/vk/type.ChromaLocationKHR.html

**Comment by AlexanderEkdahl** [comment]
Ah you are right! It correctly generates type aliases for those types! Very cool.

**Comment by MaikKlein** [comment]
Thanks @AlexanderEkdahl ash now has now ffi level support for 1.2. 

I am now starting to refactor the generator for #231 . But this will probably take longer.

In the meantime if anyone wants to expose the high level wrappers manually, feel free to do so.

**Comment by Friz64** [comment]
> In the meantime if anyone wants to expose the high level wrappers manually, feel free to do so.

I'm interested in doing so.
I have also collected a list of issues that one could fix while in the process of adding those.
- https://github.com/MaikKlein/ash/issues/258 (add the missing code)
- https://github.com/MaikKlein/ash/issues/254 (add this wrapper function because it seems to be missing)

**Comment by Friz64** [comment]
Submitted a PR for all the things i mentioned: https://github.com/MaikKlein/ash/pull/265

**Comment by cheako** [comment]
fn like DeviceV1_2::get_buffer_device_address take ```&self``` and ```device``` arguments redundantly.
https://github.com/MaikKlein/ash/blob/0.30.0/ash/src/device.rs#L169

**Comment by cheako** [comment]
AccelerationStructureBuildGeometryInfoKHRBuilder::geometry_count() should be populated from geometry() taking a slice instead of a raw ptr.

**Comment by aloucks** [comment]
@cheako Good catch. It looks like all of the methods that take `vk::Device` need to be converted to `self.handle()`.

**Comment by cheako** [comment]
destroy_ray_tracing_pipeline()? Is it just me or is this missing from the KHR RayTracing Extension?

**Comment by MaikKlein** [comment]
@cheako Yes it is just destroy pipeline.

I am closing this issue now as it is mostly finished. I fixed the device params in https://github.com/MaikKlein/ash/pull/284

**Comment by cheako** [comment]
Example: https://gitlab.com/cheako/ash-rt/-/tree/762868856fa6d50b8545b255dc0c46f59b776545
It builds, but I don't have the hardware to run it.
